### ISSUE TITLE
poe.ninja seems to have more accurate pricing than poe.watch

### ISSUE THREAD

**Issue by akaAMAZING** [Arkased/PoeFlipper#2]
Here is out.csv: http://prntscr.com/ps7tef Note the amount in the red box.

poe.watch price: http://prntscr.com/ps7tys

poe.ninja price: http://prntscr.com/ps7u5t

poe trade: http://prntscr.com/ps7uci

It's true across many other items too. Would it be possible to track poe.ninja prices instead or to use the mid ground between the two to work out the prices for profit etc?

**Comment by akaAMAZING** [comment]
I have attempted to do it myself but my knowledge with Python is limited.

I have sourced out information though to help if you're up to the task:

https://www.reddit.com/r/pathofexiledev/comments/6vxowg/list_of_poeninja_api_links/

This: https://poe.ninja/api/Data/GetDivinationCardsOverview?league=Blight is where you find the better priced Div cards.

**Comment by Arkased** [comment]
I looked into it briefly, here's the main issue. The script is currently designed to get the prices of all items from one api query, as opposed to doing different queries based on item type. I haven't been able to find a call that gets information on all items, so adding functionality to price with poe.ninja would be a lot of work I'm frankly not super interested in doing, since then purpose of the script is really just to rank the best options to flip, not calculate precise profits (which is also dependent on the specific trades made).

Let me know if you find another way.

**Comment by Arkased** [comment]
Ok looking more closely at the prices it seems that the difference is more egregious then I had initially assumed, I'll try to look more into the poe.ninja api.

**Comment by akaAMAZING** [comment]
Yeah. poe.ninja seems to have a better way to remove outliers whereas poe.watch just takes all listings into consideration.

Zerphi's Heart is a good example since the program suggests it as an amazing flip:

poe.watch price: http://prntscr.com/ptgk6b
poe.ninja price: http://prntscr.com/ptgjdl

 Seems to be much easily affected by random prices than poe.ninja is.

Appreciate it as it will help a lot for the upcoming league. I added you on Discord (Gucci), feel free to hit me up there if you need a hand with something I'm capable of :)

**Comment by akaAMAZING** [comment]
Managed to find more api links for poe.ninja:

https://poe.ninja/api/data/currencyoverview?league=Blight&type=Currency
https://poe.ninja/api/data/itemoverview?league=Blight&type=DivinationCard
https://poe.ninja/api/data/itemoverview?league=Blight&type=Prophecy
https://poe.ninja/api/data/itemoverview?league=Blight&type=UniqueWeapon
https://poe.ninja/api/data/itemoverview?league=Blight&type=UniqueArmour

Some of the links do show slight differences in price to the ones I initially mentioned which is evident if you switch between them quickly. Unsure which ones are more up to date. I'd assume the first set were.

**Comment by akaAMAZING** [comment]
I do have a suggestion though:

To simplify the multiple api queries, couldn't you set the program to query each one and to 'save' them into one. That way, it mimics the one api query that it currently makes from poe.watch?

Not sure if it works in practice, but thought I'd mention it.

**Comment by Arkased** [comment]
Oh, I would definitely do something like that, the annoying thing I'd have to implement is figuring out what item type the output item is and calling the appropriate query, either through lookup or an extra entry in the dictionary.

One thing I noticed is that my script was a lot more accurate earlier in the league. I suspect the dwindling playerbase is messing with the accuracy. I'll definitely try to get a poe.ninja version working by then, but the issue might not be as bad as it currently seems.

**Comment by Arkased** [comment]
Wait, I might be able to get away with not adding extra info if I simply concatenate the data of each individual query.

In the meantime, do you mind uploading the updated out.csv with the items you added?

**Comment by akaAMAZING** [comment]
Of course.

Uploaded as *.zip since I couldn't upload it as is:
[out.zip](https://github.com/Arkased/PoeFlipper/files/3817764/out.zip)

Would you like me to extend it to all Div cards and Prophecies?

**Comment by akaAMAZING** [comment]
Here it is for Prophecies:

[out2.zip](https://github.com/Arkased/PoeFlipper/files/3817768/out2.zip)

Once again I can add all of them if that helps.

**Comment by Arkased** [comment]
Well, I initially limited my pool to unique items within a certain price range since those are most profitable to flip. Don't do all of them unless its automated somehow, its (almost certainly) not worth the effort.

Thanks

**Comment by Arkased** [comment]
Oh crap I meant to ask for the input files to update the script with, sorry got the names mixed up.

**Comment by akaAMAZING** [comment]
I hear ya. Haha no problem, here you go:

[inputs.zip](https://github.com/Arkased/PoeFlipper/files/3818940/inputs.zip)

**Comment by Arkased** [comment]
I'm getting back into the swing of things, most of the stuff is set up, I just need to figure out the new item ids (since poe ninja and poe watch use different systems). will finish likely tomorrow or day after

**Comment by Arkased** [comment]
So I realized my current implementation (using pointers and changing their values to point to the functions corresponding to poe ninja and poe watch) is a hot mess. I'm going to work on switching over to an object-oriented model.

**Comment by Arkased** [comment]
pushed the refactor and incorporated your list with some changes, For div cards with multiple outcomes (like The Bargain with pure breachstones), I replaced the returnId with the one with the lowest price. This was done to The Bargain (pure breachstones) and Buried Treasure (sulphite scarabs). Everything else seems fine, I'm going to get the poe.ninja ids now.

**Comment by Arkased** [comment]
just pushed, should be working
