### ISSUE TITLE
Some Divs not showing up in out.csv

### ISSUE THREAD

**Issue by akaAMAZING** [Arkased/PoeFlipper#3]
I have a lot of divs in div_cards.txt and item_ids.csv with the correct reward ID's for each as shown in this image:

http://prntscr.com/psucvp

However in the output, only a handful of results show:

http://prntscr.com/psudgs

38 inputs and only 32 outputs. Any idea why?

I managed to get it working with Prophecies too and it's the same issue:

http://prntscr.com/psue24

11 inputs and 3 outputs.

**Comment by Arkased** [comment]
By default its filtering by price as well, including entries with investment between 40-2000. Delete line 11 of __init__.py thats doing the filtering:

divs = filter(utils.price_pred, divs)

**Comment by akaAMAZING** [comment]
Of course.. Should have caught that. Sorry.

Wonderful program to work with by the way, keep up the great work - 10/10.
